file<-read.table("household_power_consumption.txt",head=T,sep=";", na.strings="?",colClasses=c(rep("character",2),rep("numeric",7)))
head(file)
file1<-subset(file,Date=="1/2/2007"|Date=="2/2/2007")
png(filename="plot1.png")
hist(file1$Global_active_power,main="Global Active Power",xlab="Global Active Power (kilowatts)",col="red")
dev.off()