file<-read.table("household_power_consumption.txt",head=T,sep=";", na.strings="?",colClasses=c(rep("character",2),rep("numeric",7)))
head(file)
file1<-subset(file,Date=="1/2/2007"|Date=="2/2/2007")
file1$DateTime<-with(file1,paste(Date,Time))
file1$DateTime<-strptime(file1$DateTime,format="%d/%m/%Y %H:%M:%S")
png(filename="plot4.png")
par(mfcol=c(2,2))
with(file1,plot(DateTime,Global_active_power,ylab="Global Active Power",xlab="",type="l"))
with(file1,plot(DateTime,Sub_metering_1,ylab="Energy sub metering",xlab="",type="l",col="black"))
with(file1,points(DateTime,Sub_metering_2,type="l",col="red"))
with(file1,points(DateTime,Sub_metering_3,type="l",col="blue"))
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,bty="n")
with(file1,plot(DateTime,Voltage,xlab="datetime",type="l"))
with(file1,plot(DateTime,Global_reactive_power,xlab="datetime",type="l"))
dev.off()